name: Update Gradle Wrapper

on:
    workflow_dispatch: { }
    schedule:
        -   cron: "0 0 * * *"

permissions:
    contents: read

jobs:
    update-gradle-wrapper:
        permissions:
            contents: write # for gradle-update/update-gradle-wrapper-action
            pull-requests: write # for gradle-update/update-gradle-wrapper-action
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4.2.2
                with:
                    java-version: 21
                    distribution: adopt
            -   name: Update Gradle Wrapper
                uses: gradle-update/update-gradle-wrapper-action@v1
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
                    labels: dependencies
            -   uses: gradle/wrapper-validation-action@v1
